app/controllers/AuthController.php
<?php
namespace app\controllers;

use app\models\LoginForm;
use app\repositories\UserRepository;
use Yii;

/**
 * @author Atem Mironov <mironov2708@gmail.com>
 */
class AuthController extends BaseController
{
    /**
     * @var UserRepository
     */
    protected $users;

    /**
     * @inheritdoc
     */
    public $layout = 'empty';


    /**
     * @inheritdoc
     */
    public function init()
    {
        $this->users = new UserRepository();
    }

    /**
     * @return mixed
     */
    public function actionLogin()
    {
        if ( ! Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $this->users->getByEmail($model->email);

            if ($model->validatePassword($user)) {
                $model->login($user);
                return $this->goBack();
            }
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

app/controllers/BookController.php
<?php
namespace app\controllers;

use app\entities\Book;
use app\models\BookForm;
use app\models\BookSearch;
use app\models\ImageUploadForm;
use app\repositories\BookRepository;
use app\services\ImageUploadService;
use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * @author Atem Mironov <mironov2708@gmail.com>
 */
class BookController extends BaseController
{
    /**
     * @var BookRepository
     */
    protected $books;
    /**
     * @var ImageUploadService
     */
    protected $uploader;


    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create', 'update', 'view', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'create'],
                        'roles' => ['?', '@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update', 'view', 'delete'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function init()
    {
        $this->books = new BookRepository();
        $this->uploader = new ImageUploadService();
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new BookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        return $this->render('index', compact('dataProvider', 'searchModel'));
    }

    /**
     * @param $id
     *
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionView($id)
    {
        $model = Book::findOne($id);
        $this->ensureThat($model);

        return $this->renderPartial('_view', compact('model'));
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $redirectUrl = Yii::$app->session->get('book-create-url');
        if (is_null($redirectUrl)){
            $redirectUrl = Yii::$app->request->referrer;
            Yii::$app->session->set('book-create-url', $redirectUrl);
        }

        $model = new BookForm();

        $imageModel = new ImageUploadForm();

        if ($model->load(Yii::$app->request->post())) {
            $imageModel->file = UploadedFile::getInstance($imageModel, 'file');

            if ($imageModel->validate()) {
                $filePath = $this->uploader->saveImage($imageModel->file);
                $model->preview = $filePath;
            }

            $this->books->create($model->attributes);

            Yii::$app->session->remove('book-create-url');

            return $this->redirect($redirectUrl);
        }

        return $this->render('create',compact('model', 'imageModel'));
    }

    /**
     * @param $id
     *
     * @return string
     */
    public function actionUpdate($id)
    {
        $book = $this->books->getById($id);
        $this->ensureExists($book);

        $redirectUrl = Yii::$app->session->get('book-update-url');
        if (is_null($redirectUrl)){
            $redirectUrl = Yii::$app->request->referrer;
            Yii::$app->session->set('book-update-url', $redirectUrl);
        }

        $model = new BookForm();
        $model->setAttributes($book->attributes);

        $imageModel = new ImageUploadForm();

        if ($model->load(Yii::$app->request->post())) {
            $imageModel->file = UploadedFile::getInstance($imageModel, 'file');

            if ($imageModel->validate()) {
                $filePath = $this->uploader->saveImage($imageModel->file);
                $model->preview = $filePath;
            }

            if ($model->validate()) {
                $data = $model->attributes;

                $this->books->update($book, $data);

                $this->redirect($redirectUrl);
            }
        }

        return $this->render('update', compact('book', 'model', 'imageModel'));
    }

    /**
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $book = $this->books->getById($id);
        $this->ensureThat($book);

        $this->books->delete($book);

        return $this->redirect(Yii::$app->request->referrer);
    }
}

app/views/layouts/dashboard.php
<?php
use otsec\yii2\fladmin\DashboardAsset;
use otsec\yii2\fladmin\MainMenu;
use yii\widgets\Breadcrumbs;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this    yii\web\View */
/* @var $content string */

DashboardAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <section id="container">
        <!--header start-->
        <header class="header white-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
            </div>

            <a href="/" class="logo">
                <span>RGK</span>Group
            </a>

            <div class="top-nav">
                <?php if(!Yii::$app->user->isGuest):?>
                    <ul class="nav pull-right top-menu">
                        <li class="dropdown language">
                            <a href="<?= Url::to(['auth/logout']) ?>">
                                <span class="fa fa-unlock-alt"></span>
                                <span class="username">Выход</span>
                            </a>
                    </ul>
                <? else:?>
                    <ul class="nav pull-right top-menu">
                        <li class="dropdown language">
                            <a href="<?= Url::to(['auth/login']) ?>">
                                <span class="fa fa-unlock-alt"></span>
                                <span class="username">Вход</span>
                            </a>
                    </ul>
                <?endif?>
            </div>
        </header>
        <!--header end-->

        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse">
                <?= MainMenu::widget([
                    'encodeLabels' => false,
                    'items' => [
                        [
                            'label' => '<i class="fa fa-fw fa-users"></i> Книги',
                            'url' => ['book/index'],
                            'active' => (Yii::$app->controller->id === 'book'),
                        ],
                    ],

                ]); ?>
            </div>
        </aside>
        <!--sidebar end-->

        <!--main content start-->
        <section id="main-content">
            <section class="wrapper site-min-height">
                <?= Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    'homeLink' => ['label' => '<i class="fa fa-home"></i>', 'url' => ['default/index']],
                    'encodeLabels' => false,
                ]) ?>
                <?= $content; ?>
            </section>
        </section>
        <!--main content end-->

        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                <?= date('Y') ?> &copy; <?php echo Yii::$app->name; ?>.
                <a href="#" class="go-top">
                    <i class="fa fa-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>
    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

app/views/layouts/empty.php
<?php
use otsec\yii2\fladmin\DashboardAsset;
use yii\helpers\Html;

/* @var $this    yii\web\View */
/* @var $content string */

DashboardAsset::register($this);
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-body">
    <?php $this->beginBody() ?>

    <div class="container">
        <?= $content ?>
    </div>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>